### ISSUE TITLE
你好，我想请教一下DRM和无损音乐的事情。

### ISSUE THREAD

**Issue by guokai10000** [seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh-Monterey#4]
我的机器是10700+蓝宝石rx5600xt，现在用着igpu+dgpu一起，想问问，能不能同时实现DRM、无损播放和随航呢？

**Comment by seanzhang98** [comment]
可以，但是强制A卡解DRM之后随航画质会变得很差

**Comment by guokai10000** [comment]
﻿我成功了，而且我看随航画质还是很好啊，所以我才奇怪。
不过有时候重启了之后随航会连不上ipad。

发自我的iPhone

**Comment by guokai10000** [comment]
我错了，画质确实有影响。

发自我的iPhone

**Comment by seanzhang98** [comment]
所以建议不是一定都使用的时候关闭强制DRM
