### ISSUE TITLE
Sorry not sure where else to ask

### ISSUE THREAD

**Issue by cpoopy** [seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh-Monterey#5]
What's the application you use to check sensor info?

https://raw.githubusercontent.com/seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh-Monterey/main/imgs/sensors.png i mean this one.

Thank you in advance!

**Comment by seanzhang98** [comment]
That would be sensei, a new clean & monitor app for mac OS

**Comment by cpoopy** [comment]
Thank you very much for the info!
