### ISSUE TITLE
强制启用 AMD DRM 解码器串流服务

### ISSUE THREAD

**Issue by qin9125** [seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh-Monterey#6]
您好，强制开启AMD DRM 解码器串流服成功，我想问问怎么关闭？开启后独显的解码跟核显差太多 5k 本地视频播放直接马赛克哈哈，鱼和熊掌不可兼得 10.15 的时候可以 OC 加参数实现
关闭的命令是不是后面 yes 改为 no 呢？ 谢谢
defaults write com.apple.AppleGVA gvaForceAMDKE -boolean no

**Comment by seanzhang98** [comment]
是的
